-- ══════════════════════════════════════════════════════════════
-- PASSO 1: Criar categoria Comida Funcionário
-- ══════════════════════════════════════════════════════════════
INSERT INTO cmp_categorias (nome, plano_conta, ativo)
VALUES ('Comida Funcionário', 'Recursos Humanos', true)
ON CONFLICT (nome) DO NOTHING;

-- ══════════════════════════════════════════════════════════════
-- PASSO 2: Atualizar categoria dos produtos em est_produtos
-- ══════════════════════════════════════════════════════════════
UPDATE est_produtos
SET categoria = CASE
  WHEN UPPER(TRIM(nome)) = UPPER('PEPSI BLACK LT') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('PEPSI LT') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('FANTA LARANJA LATA') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('SUKITA LT') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MICHELOB') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('STELLA ARTOIS GOLD LN') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('STELLA ARTOIS LN') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MC CARVÃO') THEN 'Lenha/Carvão'
  WHEN UPPER(TRIM(nome)) = UPPER('MC CARVÃO PRE ASSADO') THEN 'Lenha/Carvão'
  WHEN UPPER(TRIM(nome)) = UPPER('MC ACUCAR SACHÊ') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC ADOÇANTE SACHÊ') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC BOBINA IMPRESSORA') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC COLHER REFEIÇÃO DESCARTAVEIS') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC COPO DESCART. 180ML') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC COPO DESCART. 500ML') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC COPO PLASTICO 300ML') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC ESPETO TACACA') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC FACA REFEIÇÃO') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC GARFO REFEIÇÃO') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC LUVA PLASTICA') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC LUVA VINIL TAM G') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC PENA AZUL') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC PENA VERMELHA') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC PORTA G -324 PRETA BANDEJA 4 DIVISORIAS UN') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC POTE RED 145ML') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC PRATO PLAST 23 CM') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC PRATO REFEIÇÃO') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC SAL SACHE') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC TAMPA 440ml') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC TOUCA SANFONADA') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CANUDO PRETO CAIPIRINHA') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MP PALITO DE PICOLE') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MP PALITO SACHER') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MP POTE 1000ML') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('PRATO DESCARTAVEL') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC BANDEJA DE ALUMINIO C/ TAMPA - D5') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC FILME PVC') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC BAN RET D7') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC BANDEJA D6') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC CAIXA DE FRANGO') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC CAIXA DE PEIXE') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC CANUDO SACHE 8MM SHAKE') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC CANUDO SACHE BIO FLEX 6MM') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC CAPA FARDO') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC FITA DUREX 50X50') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC GARRAFA 350ML - VIAGEM') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC GARRAFA 500ML') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC GARRAFA DE 1 LITRO') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC POTE RED 250ML') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC POTE RED 500ML P FESTA') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC POTE REDONDO C/ TAMPA PRAFESTA 750ML') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC POTE RETANGULAR 500 ML') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC PRATO DESCARTAVEL') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC SACO DE DINDIN GRANDE') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC SACO 1 KG') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC SACO 10KG') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC SACO 2 KG') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC SACOLA BRANCA - 8KG (Centro)') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC SACOLA BRANCA - 8KG (Parque)') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC SACOLA KRAFT/PARDO,LISO A_G') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC SACOLA ROTEROS') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MP PAPEL MANTEIGA') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MP SACO BOMBONS') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MC D7 FIX SUPER CONCENTRADO') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MC DESINFETANTE CONCENTRADO') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MC CLEARON CL') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MC AGUA SANITARIA') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MC ALCOOL LIQUIDO 70') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MC BALDE ESCORREDOR') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MC CLEARON') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MC DETERGENTE NEUTRO 5.LT') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MC ESPONJA COMUM') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MC FIBRA PESADA') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MC LIMPA ALUMINIO') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MC LUVA DE LIMPEZA') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MC MOP UMIDO ALGODÃO PONTA DOBRADA') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MC PANO DE CHÃO') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MC PAPEL TOALHA-TORK HANDTOWEL CENTERFEED. ROLO') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MC PERFEX WIPE') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MC PEROXY 3000') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MC SABONETE BACTERICIDA') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MC SABONETE CLIENTE') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MC SACO DE LIXO - 200LT') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MC SACO DE LIXO - 50LT') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MC SUPORTE P/ FIBRA') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MC TORK ADV GUARDANAPO XPRESSNAP CAFE 12/500') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MC TORK ADV HIG JUMBO 8/300 FS') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MC TORK ADV TOALHA INTERF 16/260 FS') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MC TORK ADV TOALHA ROLO 4/250M FS') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MC TORK SMART ONE UNIVERSAL-HIGIENICO') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MC VASSOURA') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MC X-12') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MP ALCOOL LIQUIDO') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('MP PROTETOR DE ASSENTO SANITARIO') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('SANIT CLOR') THEN 'Material de Limpeza'
  WHEN UPPER(TRIM(nome)) = UPPER('BISTECA BOVINA') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('COXA DE FRANGO') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('COXAO MOLE') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MC FARINHA FUNCIONARIO') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MC AGULHA - FUNCIONÁRIO') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MC ALFACE') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MC ARROZ - FUNCIONARIO') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MC BANANA PRATA - FUNCIONÁRIO') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MC BATATA PORTUGUESA (FUNCIONARIO)') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MC CEBOLA FUNCIONARIO') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MC CENOURA (FUNCIONARIO)') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MC COENTRO - FUNCIONÁRIO') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MC COLORAU') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MC COUVE') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MC COXA S/ COXA - FUNCIONÁRIO') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MC COXAO MOLE ISCAS') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MC EXTRADO DE TOMATE') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MC FARINHA BRANCA - FUNCIONARIO') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MC FEIJÃO CARIOCA') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MC FEIJÃO PRETO') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MC FILE DE PEITO FUNCIONÁRIO') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MC LIMÃO - FUNCIONARIO') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MC MACARRÃO - FUNCIONÁRIO') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MC MAIONESE SACHÊ - FUNCIONÁRIO') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MC MELANCIA - FUNCIONÁRIO') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MC OSSO BUCO') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MC PICADINHO CARNE - FUNCIONÁRIO') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MC PIMENTA DE CHEIRO (FUNCIONARIO)') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MC TOMATE (FUNCIONARIO)') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CALABRESA') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MP FEIJÃO DE CORDA') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MP KIT DE TAMBAQUI') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MP LEITE DE COCO') THEN 'Comida Funcionário'
  WHEN UPPER(TRIM(nome)) = UPPER('MP AGUA COM GÁS') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP AGUA SEM GÁS') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP ABSOLUT') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP APEROL 750 ML') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP BEEAFETER PINK 750ML') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP BLACK LABEL') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CACHAÇA AMBURANA') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CACHAÇA BRAZUKA 700ML') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CACHAÇA JAMBU') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CACHACA SAGATIBA') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP COINTREAL') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CURAÇAU BLUE') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP ESPUMANTE MOSCATEL') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP LICOR 43 NOVO') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP RED LABEL') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP RUM BACARDI') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP SERESTEIRO 900ml') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP TANQUERAY 750ML') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP TEQUILA PRATA') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP VINHO CABERNET SAUVIGNON') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP VINHO TINTO SUAVE QUINTA DO MORGADO 750ML') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP VODKA KETEL ONE BOTANICAS') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP VODKA SMIRNORFF') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP YPIOCA OURO 965ML') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP ALCATRA ISCA') THEN 'Proteínas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP FILÉ MIGNON INTEIRO') THEN 'Proteínas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP FRANGO A PASSARINHO') THEN 'Proteínas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP FRANGO INTEIRO') THEN 'Proteínas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP GALINHA CAIPIRA') THEN 'Proteínas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP MEDALHAO DE ALCATRA') THEN 'Proteínas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP PEITO DE FRANGO') THEN 'Proteínas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP PICADINHO DE PATINHO') THEN 'Proteínas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CORONA EXTRA') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CORONA LN') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP ORIGINAL 600ML') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP SPATEN 600ml') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP SPATEN LN') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP STELLA ARTOIS 600ML') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP STELLA ARTOIS LN') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP STELLA ARTOIS PURE GOLD LN 330ML') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP BARRIL CHOPP BRAHMA 50 LITROS') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP GAS DO CHOPP') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP ACAI') THEN 'Frios/Congelados'
  WHEN UPPER(TRIM(nome)) = UPPER('MP BACON') THEN 'Frios/Congelados'
  WHEN UPPER(TRIM(nome)) = UPPER('MP BATATA CONGELADA') THEN 'Frios/Congelados'
  WHEN UPPER(TRIM(nome)) = UPPER('MP ERVILHA CONGELADA') THEN 'Frios/Congelados'
  WHEN UPPER(TRIM(nome)) = UPPER('MP MOCOTO') THEN 'Frios/Congelados'
  WHEN UPPER(TRIM(nome)) = UPPER('MP PEITO DE PERU') THEN 'Frios/Congelados'
  WHEN UPPER(TRIM(nome)) = UPPER('MP PRESUNTO DE PERU') THEN 'Frios/Congelados'
  WHEN UPPER(TRIM(nome)) = UPPER('MP QUEIJO GORGONZOLA') THEN 'Frios/Congelados'
  WHEN UPPER(TRIM(nome)) = UPPER('MP QUEIJO MUSSARELA RALADO') THEN 'Frios/Congelados'
  WHEN UPPER(TRIM(nome)) = UPPER('MP VERDURAS CONGELADAS') THEN 'Frios/Congelados'
  WHEN UPPER(TRIM(nome)) = UPPER('MP MACARRÃO ESPAGUETE') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP MACARRÃO FETTUCCINE') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP MACARRÃO PENNE') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP AÇÚCAR') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP AMEIXA EM CALDA') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP ANIZ ESTRELADO') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP ARROZ') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP AZEITE DENDÊ') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP AZEITONA VERDE SEM CAROÇO 400G') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP BANANA CHIPS') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP BASTÃO DE GUARANA') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP BISCOITO DO CAFE') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP BOMBONS') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CANELA EM PO') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CAPSULA CAFE COM LEITE') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CAPSULA CAPUCCINO CLASSICO') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CAPSULA CHOCOLATE COM CARAMELO') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CAPSULA DE GAS') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CAPSULA EXPRESSO ATENTO') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CAPSULA EXPRESSO PLENO') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CAPSULA EXPRESSO VIBRANTE') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CEREJA CALDA') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CORANTE AZUL') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CREME DE LEITE') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CREME DE LEITE FORNEAVEL') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP EXTRATO DE TOMATE') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP FARINHA BRANCA') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP FARINHA DE ROSCA') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP FARINHA DE TAPIOCA') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP FARINHA OVINHA') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP FARINHA PANKO') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP FEIJÃO CARIOCA') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP FEIJÃO DE PRAIA') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP KETCHUP') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP LEITE CONDENSADO') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP LEITE EM PO INTEGRAL') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP LEITE LIQUIDO INTEGRAL') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP MARGARINA') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP MASSA DE PURÊ DE BATATA') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP MILHO VERDE LATA') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP MOLHO SHOYU') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP NOZ MOSCADA') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP OLEO COMPOSTO') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP OLEO DE ALGODÃO 900ML') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP OLEO DE SOJA') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP OVO') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP PALMITO') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP PAO FRANCES PRODUÇÃO') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP PIMENTA DO REINO EM GRAOS') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP PIMENTA ROSA') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP SAL GROSSO') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP SAL REFINADO') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP TRIGO S/ FERMENTO') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP VINAGRE') THEN 'Estivas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CATUPIRY REQUEIJAO') THEN 'Frios/Congelados'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CREAM CHEESE') THEN 'Frios/Congelados'
  WHEN UPPER(TRIM(nome)) = UPPER('MP MASSA DE PASTEL 500GR') THEN 'Frios/Congelados'
  WHEN UPPER(TRIM(nome)) = UPPER('MP QUEIJO COALHO') THEN 'Frios/Congelados'
  WHEN UPPER(TRIM(nome)) = UPPER('MP QUEIJO MUSSARELA BARRA') THEN 'Frios/Congelados'
  WHEN UPPER(TRIM(nome)) = UPPER('MP QUEIJO MUSSARELA FATIADO') THEN 'Frios/Congelados'
  WHEN UPPER(TRIM(nome)) = UPPER('MP QUEIJO PARMESAO TIPO 1') THEN 'Frios/Congelados'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CAMARÃO FRESCO S/CABEÇA M') THEN 'Proteínas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CAMARÃO SECO G') THEN 'Proteínas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CAMARÃO SECO M') THEN 'Proteínas'
  WHEN UPPER(TRIM(nome)) = UPPER('MC PEPINO') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP ABACAXI') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP ABOBORA') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP ALECRIM') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP ALFACE AMERICANA REGIONAL') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP ALFACE BOLA') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP ALFAVACA') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP ALHO DESCASCADO') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP BANANA PACOVA') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP BATATA PORTUGUESA') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CASTANHA DO BRASIL') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CASTANHA TRITURADA') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CEBOLA') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CENOURA') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CHICORIA') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP COCO SECO') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP COENTRO') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP FOLHA DE BANANA') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP GOMA') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP HORTELÃ') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP JAMBU') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP LARANJA') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP LARANJA BAHIA') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP LIMÃO') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP LIMAO SICILIANO') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP MAÇA VERDE') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP MACAXEIRA') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP MARACUJA FRUTA') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP MAXIXE') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP MORANGO FRUTA') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP PIMENTA DE CHEIRO') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP PIMENTA MURUPI') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP PITAYA') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP REPOLHO VERDE') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP SEMENTE DE URUCUM') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP TANGERINA') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP TOMATE') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP TUCUMA') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP TUCUPI') THEN 'Hortifruti'
  WHEN UPPER(TRIM(nome)) = UPPER('MP COSTELA DE TAMBAQUI') THEN 'Proteínas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP JARAQUI') THEN 'Proteínas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP MATRINXA') THEN 'Proteínas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP PICADINHO DE TAMBAQUI') THEN 'Proteínas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP PIRARUCU FRESCO') THEN 'Proteínas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP PIRARUCU SECO') THEN 'Proteínas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP SARDINHA') THEN 'Proteínas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP TAMBAQUI 2,300 MEDIA CASACA') THEN 'Proteínas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP TAMBAQUI 3,000 MEDIA') THEN 'Proteínas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP TAMBAQUI DESCAMADO') THEN 'Proteínas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP POLPA ACEROLA') THEN 'Polpas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP POLPA CUPUACU 1KG') THEN 'Polpas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP POLPA DE CAJU') THEN 'Polpas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP POLPA DE CUPUAÇU') THEN 'Polpas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP POLPA GOIABA') THEN 'Polpas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP POLPA GRAVIOLA') THEN 'Polpas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP POLPA MANGA') THEN 'Polpas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP POLPA MANGA 1KG') THEN 'Polpas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP POLPA MARACUJÁ') THEN 'Polpas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP POLPA TAPEREBÁ') THEN 'Polpas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP POLPA TAPEREBÁ 1KG') THEN 'Polpas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP BARE 1 LT') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP COCA COLA 1,5 L') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP COCA COLA ZERO 1,5L') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP BARE DE 2 LITROS') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP BARE LATA') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP COCA COLA LATA') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP COCA COLA ZERO LATA') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP FANTA LARANJA LATA') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP FANTA UVA LATA') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP GUARANA ANTARTICA LATA') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP GUARANA ANTARTICA ZERO 2LT') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP GUARANA DIET LATA') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP MONSTER MELAN LT 473ML') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP SCHWEPPES CITRUS LATA') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP SCHWEPPES TONICA LATA') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP SODA LATA') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP SPRITE LATA') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP TONICA ANTARTICA 355 ml') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP TUCHAUA LATA') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP TORTA CUPUACU COM CHOCOLATE') THEN 'Sobremesas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP TORTA CUPUACU COM DOCE') THEN 'Sobremesas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP BROWNIE DE CHOCOLATE') THEN 'Sobremesas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CEU DE BRIGADEIRO') THEN 'Sobremesas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP CHEESECAKE CHOCOLATE COM CUPUACU') THEN 'Sobremesas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP PETIT GATEAU C CALDA') THEN 'Sobremesas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP PICOLE DE ACAI') THEN 'Sobremesas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP PICOLE DE GRAVIOLA') THEN 'Sobremesas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP PUDIM DE LEITE') THEN 'Sobremesas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP SORVETE DE CREME') THEN 'Sobremesas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP SORVETE DE TAPIOCA') THEN 'Sobremesas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP TORTA ABACAXI') THEN 'Sobremesas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP EMULSIFICANTE') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP MEL DE ABELHA') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP MELADO DE CANA') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP PHISSALYS') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP XAROPE DE GUARANA MAGISTRAL') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP XAROPE DE LARANJA (1)') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP XAROPE DE LARANJA (2)') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP XAROPE DE MORANGO') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MP XAROPE LIMÃO SICILIANO') THEN 'Bebidas'
  WHEN UPPER(TRIM(nome)) = UPPER('MU ACENDEDOR') THEN 'Descartável/Embalagens'
  WHEN UPPER(TRIM(nome)) = UPPER('MU MOLHEIRA') THEN 'Descartável/Embalagens'
  ELSE categoria
END
WHERE UPPER(TRIM(nome)) IN (
UPPER('PEPSI BLACK LT'),
UPPER('PEPSI LT'),
UPPER('FANTA LARANJA LATA'),
UPPER('SUKITA LT'),
UPPER('MICHELOB'),
UPPER('STELLA ARTOIS GOLD LN'),
UPPER('STELLA ARTOIS LN'),
UPPER('MC CARVÃO'),
UPPER('MC CARVÃO PRE ASSADO'),
UPPER('MC ACUCAR SACHÊ'),
UPPER('MC ADOÇANTE SACHÊ'),
UPPER('MC BOBINA IMPRESSORA'),
UPPER('MC COLHER REFEIÇÃO DESCARTAVEIS'),
UPPER('MC COPO DESCART. 180ML'),
UPPER('MC COPO DESCART. 500ML'),
UPPER('MC COPO PLASTICO 300ML'),
UPPER('MC ESPETO TACACA'),
UPPER('MC FACA REFEIÇÃO'),
UPPER('MC GARFO REFEIÇÃO'),
UPPER('MC LUVA PLASTICA'),
UPPER('MC LUVA VINIL TAM G'),
UPPER('MC PENA AZUL'),
UPPER('MC PENA VERMELHA'),
UPPER('MC PORTA G -324 PRETA BANDEJA 4 DIVISORIAS UN'),
UPPER('MC POTE RED 145ML'),
UPPER('MC PRATO PLAST 23 CM'),
UPPER('MC PRATO REFEIÇÃO'),
UPPER('MC SAL SACHE'),
UPPER('MC TAMPA 440ml'),
UPPER('MC TOUCA SANFONADA'),
UPPER('MP CANUDO PRETO CAIPIRINHA'),
UPPER('MP PALITO DE PICOLE'),
UPPER('MP PALITO SACHER'),
UPPER('MP POTE 1000ML'),
UPPER('PRATO DESCARTAVEL'),
UPPER('MC BANDEJA DE ALUMINIO C/ TAMPA - D5'),
UPPER('MC FILME PVC'),
UPPER('MC BAN RET D7'),
UPPER('MC BANDEJA D6'),
UPPER('MC CAIXA DE FRANGO'),
UPPER('MC CAIXA DE PEIXE'),
UPPER('MC CANUDO SACHE 8MM SHAKE'),
UPPER('MC CANUDO SACHE BIO FLEX 6MM'),
UPPER('MC CAPA FARDO'),
UPPER('MC FITA DUREX 50X50'),
UPPER('MC GARRAFA 350ML - VIAGEM'),
UPPER('MC GARRAFA 500ML'),
UPPER('MC GARRAFA DE 1 LITRO'),
UPPER('MC POTE RED 250ML'),
UPPER('MC POTE RED 500ML P FESTA'),
UPPER('MC POTE REDONDO C/ TAMPA PRAFESTA 750ML'),
UPPER('MC POTE RETANGULAR 500 ML'),
UPPER('MC PRATO DESCARTAVEL'),
UPPER('MC SACO DE DINDIN GRANDE'),
UPPER('MC SACO 1 KG'),
UPPER('MC SACO 10KG'),
UPPER('MC SACO 2 KG'),
UPPER('MC SACOLA BRANCA - 8KG (Centro)'),
UPPER('MC SACOLA BRANCA - 8KG (Parque)'),
UPPER('MC SACOLA KRAFT/PARDO,LISO A_G'),
UPPER('MC SACOLA ROTEROS'),
UPPER('MP PAPEL MANTEIGA'),
UPPER('MP SACO BOMBONS'),
UPPER('MC D7 FIX SUPER CONCENTRADO'),
UPPER('MC DESINFETANTE CONCENTRADO'),
UPPER('MC CLEARON CL'),
UPPER('MC AGUA SANITARIA'),
UPPER('MC ALCOOL LIQUIDO 70'),
UPPER('MC BALDE ESCORREDOR'),
UPPER('MC CLEARON'),
UPPER('MC DETERGENTE NEUTRO 5.LT'),
UPPER('MC ESPONJA COMUM'),
UPPER('MC FIBRA PESADA'),
UPPER('MC LIMPA ALUMINIO'),
UPPER('MC LUVA DE LIMPEZA'),
UPPER('MC MOP UMIDO ALGODÃO PONTA DOBRADA'),
UPPER('MC PANO DE CHÃO'),
UPPER('MC PAPEL TOALHA-TORK HANDTOWEL CENTERFEED. ROLO'),
UPPER('MC PERFEX WIPE'),
UPPER('MC PEROXY 3000'),
UPPER('MC SABONETE BACTERICIDA'),
UPPER('MC SABONETE CLIENTE'),
UPPER('MC SACO DE LIXO - 200LT'),
UPPER('MC SACO DE LIXO - 50LT'),
UPPER('MC SUPORTE P/ FIBRA'),
UPPER('MC TORK ADV GUARDANAPO XPRESSNAP CAFE 12/500'),
UPPER('MC TORK ADV HIG JUMBO 8/300 FS'),
UPPER('MC TORK ADV TOALHA INTERF 16/260 FS'),
UPPER('MC TORK ADV TOALHA ROLO 4/250M FS'),
UPPER('MC TORK SMART ONE UNIVERSAL-HIGIENICO'),
UPPER('MC VASSOURA'),
UPPER('MC X-12'),
UPPER('MP ALCOOL LIQUIDO'),
UPPER('MP PROTETOR DE ASSENTO SANITARIO'),
UPPER('SANIT CLOR'),
UPPER('BISTECA BOVINA'),
UPPER('COXA DE FRANGO'),
UPPER('COXAO MOLE'),
UPPER('MC FARINHA FUNCIONARIO'),
UPPER('MC AGULHA - FUNCIONÁRIO'),
UPPER('MC ALFACE'),
UPPER('MC ARROZ - FUNCIONARIO'),
UPPER('MC BANANA PRATA - FUNCIONÁRIO'),
UPPER('MC BATATA PORTUGUESA (FUNCIONARIO)'),
UPPER('MC CEBOLA FUNCIONARIO'),
UPPER('MC CENOURA (FUNCIONARIO)'),
UPPER('MC COENTRO - FUNCIONÁRIO'),
UPPER('MC COLORAU'),
UPPER('MC COUVE'),
UPPER('MC COXA S/ COXA - FUNCIONÁRIO'),
UPPER('MC COXAO MOLE ISCAS'),
UPPER('MC EXTRADO DE TOMATE'),
UPPER('MC FARINHA BRANCA - FUNCIONARIO'),
UPPER('MC FEIJÃO CARIOCA'),
UPPER('MC FEIJÃO PRETO'),
UPPER('MC FILE DE PEITO FUNCIONÁRIO'),
UPPER('MC LIMÃO - FUNCIONARIO'),
UPPER('MC MACARRÃO - FUNCIONÁRIO'),
UPPER('MC MAIONESE SACHÊ - FUNCIONÁRIO'),
UPPER('MC MELANCIA - FUNCIONÁRIO'),
UPPER('MC OSSO BUCO'),
UPPER('MC PICADINHO CARNE - FUNCIONÁRIO'),
UPPER('MC PIMENTA DE CHEIRO (FUNCIONARIO)'),
UPPER('MC TOMATE (FUNCIONARIO)'),
UPPER('MP CALABRESA'),
UPPER('MP FEIJÃO DE CORDA'),
UPPER('MP KIT DE TAMBAQUI'),
UPPER('MP LEITE DE COCO'),
UPPER('MP AGUA COM GÁS'),
UPPER('MP AGUA SEM GÁS'),
UPPER('MP ABSOLUT'),
UPPER('MP APEROL 750 ML'),
UPPER('MP BEEAFETER PINK 750ML'),
UPPER('MP BLACK LABEL'),
UPPER('MP CACHAÇA AMBURANA'),
UPPER('MP CACHAÇA BRAZUKA 700ML'),
UPPER('MP CACHAÇA JAMBU'),
UPPER('MP CACHACA SAGATIBA'),
UPPER('MP COINTREAL'),
UPPER('MP CURAÇAU BLUE'),
UPPER('MP ESPUMANTE MOSCATEL'),
UPPER('MP LICOR 43 NOVO'),
UPPER('MP RED LABEL'),
UPPER('MP RUM BACARDI'),
UPPER('MP SERESTEIRO 900ml'),
UPPER('MP TANQUERAY 750ML'),
UPPER('MP TEQUILA PRATA'),
UPPER('MP VINHO CABERNET SAUVIGNON'),
UPPER('MP VINHO TINTO SUAVE QUINTA DO MORGADO 750ML'),
UPPER('MP VODKA KETEL ONE BOTANICAS'),
UPPER('MP VODKA SMIRNORFF'),
UPPER('MP YPIOCA OURO 965ML'),
UPPER('MP ALCATRA ISCA'),
UPPER('MP FILÉ MIGNON INTEIRO'),
UPPER('MP FRANGO A PASSARINHO'),
UPPER('MP FRANGO INTEIRO'),
UPPER('MP GALINHA CAIPIRA'),
UPPER('MP MEDALHAO DE ALCATRA'),
UPPER('MP PEITO DE FRANGO'),
UPPER('MP PICADINHO DE PATINHO'),
UPPER('MP CORONA EXTRA'),
UPPER('MP CORONA LN'),
UPPER('MP ORIGINAL 600ML'),
UPPER('MP SPATEN 600ml'),
UPPER('MP SPATEN LN'),
UPPER('MP STELLA ARTOIS 600ML'),
UPPER('MP STELLA ARTOIS LN'),
UPPER('MP STELLA ARTOIS PURE GOLD LN 330ML'),
UPPER('MP BARRIL CHOPP BRAHMA 50 LITROS'),
UPPER('MP GAS DO CHOPP'),
UPPER('MP ACAI'),
UPPER('MP BACON'),
UPPER('MP BATATA CONGELADA'),
UPPER('MP ERVILHA CONGELADA'),
UPPER('MP MOCOTO'),
UPPER('MP PEITO DE PERU'),
UPPER('MP PRESUNTO DE PERU'),
UPPER('MP QUEIJO GORGONZOLA'),
UPPER('MP QUEIJO MUSSARELA RALADO'),
UPPER('MP VERDURAS CONGELADAS'),
UPPER('MP MACARRÃO ESPAGUETE'),
UPPER('MP MACARRÃO FETTUCCINE'),
UPPER('MP MACARRÃO PENNE'),
UPPER('MP AÇÚCAR'),
UPPER('MP AMEIXA EM CALDA'),
UPPER('MP ANIZ ESTRELADO'),
UPPER('MP ARROZ'),
UPPER('MP AZEITE DENDÊ'),
UPPER('MP AZEITONA VERDE SEM CAROÇO 400G'),
UPPER('MP BANANA CHIPS'),
UPPER('MP BASTÃO DE GUARANA'),
UPPER('MP BISCOITO DO CAFE'),
UPPER('MP BOMBONS'),
UPPER('MP CANELA EM PO'),
UPPER('MP CAPSULA CAFE COM LEITE'),
UPPER('MP CAPSULA CAPUCCINO CLASSICO'),
UPPER('MP CAPSULA CHOCOLATE COM CARAMELO'),
UPPER('MP CAPSULA DE GAS'),
UPPER('MP CAPSULA EXPRESSO ATENTO'),
UPPER('MP CAPSULA EXPRESSO PLENO'),
UPPER('MP CAPSULA EXPRESSO VIBRANTE'),
UPPER('MP CEREJA CALDA'),
UPPER('MP CORANTE AZUL'),
UPPER('MP CREME DE LEITE'),
UPPER('MP CREME DE LEITE FORNEAVEL'),
UPPER('MP EXTRATO DE TOMATE'),
UPPER('MP FARINHA BRANCA'),
UPPER('MP FARINHA DE ROSCA'),
UPPER('MP FARINHA DE TAPIOCA'),
UPPER('MP FARINHA OVINHA'),
UPPER('MP FARINHA PANKO'),
UPPER('MP FEIJÃO CARIOCA'),
UPPER('MP FEIJÃO DE PRAIA'),
UPPER('MP KETCHUP'),
UPPER('MP LEITE CONDENSADO'),
UPPER('MP LEITE EM PO INTEGRAL'),
UPPER('MP LEITE LIQUIDO INTEGRAL'),
UPPER('MP MARGARINA'),
UPPER('MP MASSA DE PURÊ DE BATATA'),
UPPER('MP MILHO VERDE LATA'),
UPPER('MP MOLHO SHOYU'),
UPPER('MP NOZ MOSCADA'),
UPPER('MP OLEO COMPOSTO'),
UPPER('MP OLEO DE ALGODÃO 900ML'),
UPPER('MP OLEO DE SOJA'),
UPPER('MP OVO'),
UPPER('MP PALMITO'),
UPPER('MP PAO FRANCES PRODUÇÃO'),
UPPER('MP PIMENTA DO REINO EM GRAOS'),
UPPER('MP PIMENTA ROSA'),
UPPER('MP SAL GROSSO'),
UPPER('MP SAL REFINADO'),
UPPER('MP TRIGO S/ FERMENTO'),
UPPER('MP VINAGRE'),
UPPER('MP CATUPIRY REQUEIJAO'),
UPPER('MP CREAM CHEESE'),
UPPER('MP MASSA DE PASTEL 500GR'),
UPPER('MP QUEIJO COALHO'),
UPPER('MP QUEIJO MUSSARELA BARRA'),
UPPER('MP QUEIJO MUSSARELA FATIADO'),
UPPER('MP QUEIJO PARMESAO TIPO 1'),
UPPER('MP CAMARÃO FRESCO S/CABEÇA M'),
UPPER('MP CAMARÃO SECO G'),
UPPER('MP CAMARÃO SECO M'),
UPPER('MC PEPINO'),
UPPER('MP ABACAXI'),
UPPER('MP ABOBORA'),
UPPER('MP ALECRIM'),
UPPER('MP ALFACE AMERICANA REGIONAL'),
UPPER('MP ALFACE BOLA'),
UPPER('MP ALFAVACA'),
UPPER('MP ALHO DESCASCADO'),
UPPER('MP BANANA PACOVA'),
UPPER('MP BATATA PORTUGUESA'),
UPPER('MP CASTANHA DO BRASIL'),
UPPER('MP CASTANHA TRITURADA'),
UPPER('MP CEBOLA'),
UPPER('MP CENOURA'),
UPPER('MP CHICORIA'),
UPPER('MP COCO SECO'),
UPPER('MP COENTRO'),
UPPER('MP FOLHA DE BANANA'),
UPPER('MP GOMA'),
UPPER('MP HORTELÃ'),
UPPER('MP JAMBU'),
UPPER('MP LARANJA'),
UPPER('MP LARANJA BAHIA'),
UPPER('MP LIMÃO'),
UPPER('MP LIMAO SICILIANO'),
UPPER('MP MAÇA VERDE'),
UPPER('MP MACAXEIRA'),
UPPER('MP MARACUJA FRUTA'),
UPPER('MP MAXIXE'),
UPPER('MP MORANGO FRUTA'),
UPPER('MP PIMENTA DE CHEIRO'),
UPPER('MP PIMENTA MURUPI'),
UPPER('MP PITAYA'),
UPPER('MP REPOLHO VERDE'),
UPPER('MP SEMENTE DE URUCUM'),
UPPER('MP TANGERINA'),
UPPER('MP TOMATE'),
UPPER('MP TUCUMA'),
UPPER('MP TUCUPI'),
UPPER('MP COSTELA DE TAMBAQUI'),
UPPER('MP JARAQUI'),
UPPER('MP MATRINXA'),
UPPER('MP PICADINHO DE TAMBAQUI'),
UPPER('MP PIRARUCU FRESCO'),
UPPER('MP PIRARUCU SECO'),
UPPER('MP SARDINHA'),
UPPER('MP TAMBAQUI 2,300 MEDIA CASACA'),
UPPER('MP TAMBAQUI 3,000 MEDIA'),
UPPER('MP TAMBAQUI DESCAMADO'),
UPPER('MP POLPA ACEROLA'),
UPPER('MP POLPA CUPUACU 1KG'),
UPPER('MP POLPA DE CAJU'),
UPPER('MP POLPA DE CUPUAÇU'),
UPPER('MP POLPA GOIABA'),
UPPER('MP POLPA GRAVIOLA'),
UPPER('MP POLPA MANGA'),
UPPER('MP POLPA MANGA 1KG'),
UPPER('MP POLPA MARACUJÁ'),
UPPER('MP POLPA TAPEREBÁ'),
UPPER('MP POLPA TAPEREBÁ 1KG'),
UPPER('MP BARE 1 LT'),
UPPER('MP COCA COLA 1,5 L'),
UPPER('MP COCA COLA ZERO 1,5L'),
UPPER('MP BARE DE 2 LITROS'),
UPPER('MP BARE LATA'),
UPPER('MP COCA COLA LATA'),
UPPER('MP COCA COLA ZERO LATA'),
UPPER('MP FANTA LARANJA LATA'),
UPPER('MP FANTA UVA LATA'),
UPPER('MP GUARANA ANTARTICA LATA'),
UPPER('MP GUARANA ANTARTICA ZERO 2LT'),
UPPER('MP GUARANA DIET LATA'),
UPPER('MP MONSTER MELAN LT 473ML'),
UPPER('MP SCHWEPPES CITRUS LATA'),
UPPER('MP SCHWEPPES TONICA LATA'),
UPPER('MP SODA LATA'),
UPPER('MP SPRITE LATA'),
UPPER('MP TONICA ANTARTICA 355 ml'),
UPPER('MP TUCHAUA LATA'),
UPPER('MP TORTA CUPUACU COM CHOCOLATE'),
UPPER('MP TORTA CUPUACU COM DOCE'),
UPPER('MP BROWNIE DE CHOCOLATE'),
UPPER('MP CEU DE BRIGADEIRO'),
UPPER('MP CHEESECAKE CHOCOLATE COM CUPUACU'),
UPPER('MP PETIT GATEAU C CALDA'),
UPPER('MP PICOLE DE ACAI'),
UPPER('MP PICOLE DE GRAVIOLA'),
UPPER('MP PUDIM DE LEITE'),
UPPER('MP SORVETE DE CREME'),
UPPER('MP SORVETE DE TAPIOCA'),
UPPER('MP TORTA ABACAXI'),
UPPER('MP EMULSIFICANTE'),
UPPER('MP MEL DE ABELHA'),
UPPER('MP MELADO DE CANA'),
UPPER('MP PHISSALYS'),
UPPER('MP XAROPE DE GUARANA MAGISTRAL'),
UPPER('MP XAROPE DE LARANJA (1)'),
UPPER('MP XAROPE DE LARANJA (2)'),
UPPER('MP XAROPE DE MORANGO'),
UPPER('MP XAROPE LIMÃO SICILIANO'),
UPPER('MU ACENDEDOR'),
UPPER('MU MOLHEIRA')
);

NOTIFY pgrst, 'reload schema';