const SB_URL = 'https://pwmpqdaaogrrdlqxcqev.supabase.co';
const SB_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3bXBxZGFhb2dycmRscXhjcWV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk0NTM5MDYsImV4cCI6MjA5NTAyOTkwNn0.NCsE48pa8mv7mtU3bCtZEmyE5uT5yQVq-kVT7AUCjQI';
